// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABINfA6wrL9kd9Xip5bUkF4g3wOge4l9U',
    appId: '1:882309797249:web:9fddc9a784fbd29019c480',
    messagingSenderId: '882309797249',
    projectId: 'expensetracker-bc4a6',
    authDomain: 'expensetracker-bc4a6.firebaseapp.com',
    storageBucket: 'expensetracker-bc4a6.firebasestorage.app',
    measurementId: 'G-LEJPRYVPMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf679gPaVeVHFzr4tKBkI-fP6qQ6czc28',
    appId: '1:882309797249:android:c3cfba4d6a6050d719c480',
    messagingSenderId: '882309797249',
    projectId: 'expensetracker-bc4a6',
    storageBucket: 'expensetracker-bc4a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifpy5qQ7eIoErgYMmltuwZDSxWGD6aMY',
    appId: '1:882309797249:ios:88122cea71a5121e19c480',
    messagingSenderId: '882309797249',
    projectId: 'expensetracker-bc4a6',
    storageBucket: 'expensetracker-bc4a6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
